language: r
sudo: required

r_binary_packages:
- rmarkdown

r_github_packages:
- ropensci/USAboundariesData

warnings_are_errors: true

notifications:
  slack:
    secure: F3ywEGAskqvJ6BlCXZgGPjUZkeSN+KRFbHpgKvVaMcf1nSMDfMSDS7X4rgGLLzHMu5lPbu/G69Hw7ousXFiO+b0cWShQcAK6xDYBGXs2MqmQLws3iFFnUKMjHQVwBpTcMPitsqU8gR27xWnC+Du5jzJ7amAO54LxfK3BPHm7cDg=
  email:
    on_success: change
    on_failure: always
